name: "CS"

on:
  pull_request:
    branches:
      - master
      - 1.x
  push:
    branches:
      - master
      - 1.x

env:
  SYMFONY_PHPUNIT_VERSION: 7.5

jobs:
  coding-standards:
    name: "CS Fixer & PHPStan"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php:
          - "7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php }}"
          tools: cs2pr, composer:v2
          ini-values: "date.timezone=Europe/Paris"
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Add PHPStan"
        run: "composer require phpstan/phpstan phpstan/phpstan-phpunit --dev --no-progress --no-suggest"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--optimize-autoloader --prefer-dist"

      - name: "Run PHP CS Fixer"
        run: "php vendor/bin/php-cs-fixer fix --verbose --dry-run --format=checkstyle | cs2pr"

      - name: "Install PHPUnit for PHPStan"
        run: "php vendor/bin/simple-phpunit install"

      - name: "Run PHPStan"
        run: "php vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr"
